#!/usr/bin/env bash
# Coverage runner for the polyrouter test suite (CALIDAD #15).
#
# Measures hooks/lib/*.py + hooks/classify-prompt.py — the routing pipeline.
# Generates assets/coverage.svg and docs/COVERAGE.md, and exits non-zero if
# total coverage drops below ${COVERAGE_MIN} (default 80%) so the script
# acts as a quality gate consistent with scripts/poly-accuracy.py.
#
# Usage:
#   scripts/poly-coverage.sh                  # full run, hard 80% gate
#   COVERAGE_MIN=85 scripts/poly-coverage.sh  # raise the gate
#   scripts/poly-coverage.sh --no-gate        # report only, do not fail

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

COVERAGE_MIN="${COVERAGE_MIN:-80}"
GATE=1
for arg in "$@"; do
    case "$arg" in
        --no-gate) GATE=0 ;;
        *) echo "warn: unknown arg '$arg' (ignored)" >&2 ;;
    esac
done

# Pick a Python that has coverage installed: prefer .venv-dev, fall back to
# system python. Avoid silently running with the wrong interpreter.
if [[ -x ".venv-dev/bin/python" ]] && .venv-dev/bin/python -c "import coverage" 2>/dev/null; then
    PY=".venv-dev/bin/python"
elif command -v python3 >/dev/null && python3 -c "import coverage" 2>/dev/null; then
    PY="python3"
else
    cat >&2 <<EOF
error: coverage is not installed.

Install dev dependencies first:
    uv venv .venv-dev
    VIRTUAL_ENV=.venv-dev uv pip install -r requirements-dev.txt

Then re-run: scripts/poly-coverage.sh
EOF
    exit 2
fi

echo "Using Python: $PY"
echo "Coverage gate: ${COVERAGE_MIN}% (--no-gate to disable)"

# Clean any prior partial data so the report is reproducible.
rm -f .coverage

# --include scopes the measurement to the unit-testable routing surface:
# hooks/lib/*.py — the pure modules that the test suite drives directly.
#
# We do NOT include hooks/classify-prompt.py here. That file's main()
# (~390 lines, ~30% of the script) is stdin/stdout orchestration glue
# that's exercised in production every routed prompt but has no unit
# tests; mixing it into the gate either inflates via "# pragma: no
# cover" masks or forces a stdin-driven integration rig. The lib
# modules ARE the deterministic, testable surface — pushing the gate
# there gives a number that means what the badge claims it means.
"$PY" -m coverage run \
    --include='hooks/lib/*.py' \
    -m pytest -q

mkdir -p assets docs

# SVG badge — the canonical artifact rendered by README.
"$PY" -m coverage_badge -o assets/coverage.svg -f

# Per-module breakdown — copy of `coverage report` output, plus a header.
{
    echo "# Coverage Report"
    echo
    echo "Generated by \`scripts/poly-coverage.sh\` (CALIDAD #15)."
    echo
    echo "Scope: \`hooks/lib/*.py\` (the unit-testable routing modules)."
    echo
    echo "\`hooks/classify-prompt.py\` is intentionally **not** in scope — its"
    echo "\`main()\` is ~390 lines of stdin/stdout orchestration glue exercised"
    echo "in production every routed prompt. Including it would either inflate"
    echo "the percentage via \`# pragma: no cover\` masks or force a stdin"
    echo "integration rig; the lib modules are the deterministic, testable"
    echo "surface, so the badge reflects that surface honestly."
    echo
    echo '```'
    "$PY" -m coverage report -m
    echo '```'
} > docs/COVERAGE.md

# Extract the total percentage to drive the gate. `coverage report` final
# row is "TOTAL  ...  XX%" — pull XX with awk for portability.
TOTAL=$("$PY" -m coverage report | awk '/^TOTAL/ { gsub("%", "", $NF); print $NF }')

echo
echo "Total coverage: ${TOTAL}%"
echo "Wrote assets/coverage.svg"
echo "Wrote docs/COVERAGE.md"

if [[ "$GATE" == "1" ]]; then
    # Compare with python (handles non-integer percentages).
    BELOW=$("$PY" -c "import sys; sys.exit(0 if float('$TOTAL') >= float('$COVERAGE_MIN') else 1)" \
        && echo 0 || echo 1)
    if [[ "$BELOW" == "1" ]]; then
        echo "FAIL: ${TOTAL}% < ${COVERAGE_MIN}% (gate)" >&2
        exit 1
    fi
    echo "PASS: ${TOTAL}% >= ${COVERAGE_MIN}% (gate)"
fi
